---
  - name: create build directory
    file:
      path: ~/tmp/tomcat-deploy-files
      state: directory
      owner: "{{ ansible_user | default('root') }}"
      group: "{{ ansible_user | default('root') }}"
      mode: '0755'
  - name: copy Dockerfile
    copy:
      src: "files/{{ dockerfile_name }}"
      dest: ~/tmp/tomcat-deploy-files
      owner: "{{ ansible_user | default('root') }}"
      group: "{{ ansible_user | default('root') }}"
      mode: '0644'

  - name: build container image
    community.docker.docker_image:
      name: "{{ image_name }}"
      tag: "{{ image_tag | default('latest') }}"
      build:
        path: "~/tmp/tomcat-deploy-files"
        dockerfile: "{{ dockerfile_name }}"
        pull: no
        nocache: yes
        args: "{{ docker_image_args }}"
      source: build
    become: yes
