---
- name: assert required vars
  include_tasks: "00_assert_required_vars.yml"

- name: build tomcat sample container image
  include_tasks: "01_build_container_image.yml"

- name: run tomcat sample container image
  include_tasks: "02_run_container_image.yml"
