---
- name: Create container
  community.docker.docker_container:
    name: "{{ container_name }}"
    image: "{{ image_name }}:{{ image_tag }}"
    detach: yes
    cleanup: yes
    container_default_behavior: no_defaults
    exposed_ports:
      - "{{ container_port }}"
    ports:
      - "{{ host_map_port }}:{{ container_port }}"
