---
- name: assert required vars
  assert:
    that: "{{ item }} is defined"
  loop:
    - "script_test_name"
    - "container_test_params"
  loop_control:
    label: "Evaluating variable {{ item }}"
