---  
#This tasks copy the files to run the tests
- name: create tests directory
  file:
    path: ~/tmp/tomcat-tests-files
    state: directory
    owner: "{{ ansible_user | default('root') }}"
    group: "{{ ansible_user | default('root') }}"
    mode: '0755'
  become: yes
- name: copy test file
  copy:
    src: "files/{{ script_test_name }}"
    dest: ~/tmp/tomcat-tests-files
    owner: "{{ ansible_user | default('root') }}"
    group: "{{ ansible_user | default('root') }}"
    mode: '0644'
  become: yes
