---
- name: execute pytest script
  script: "files/wrap_tests.py /root/tmp/tomcat-tests-files/{{ script_test_name }} '{{ container_test_params | to_json }}'"
  register: pytest_execution
  args:
    executable: python3
  failed_when: no
  changed_when: no
  become: yes

- debug: 
    var: pytest_execution
    verbosity: 2

- name: display return code
  debug:
    msg:
      - "Return code is {{ pytest_execution.rc }}"
      - "{% if pytest_execution.rc==0 %}All tests passed successfully. Container is up and running{% elif pytest_execution.rc==1 %}Some test failed{% else %}Test crashed, checkout the test parameters{% endif %}"
  failed_when: "pytest_execution.rc==2"

