---
- name: execute pytest script
  script: "files/wrap_tests.py /root/tmp/tomcat-tests-files/{{ script_test_name }} '{{ container_test_params | to_json }}'"
  register: pytest_execution
  args:
    executable: python3
  failed_when: no
  changed_when: no

- name: display return code
  debug:
    msg:
      - "Return code is {{ pytest_execution.rc }}"
      - "{% if pytest_execution.rc==0 %}All tests passed successfully{% elif pytest_execution.rc==1 %}Some test failed{% else %}Test crashed{% endif %}"
