---  
- name: create build directory
  file:
    path: /root/tmp/tomcat-tests-files
    state: directory
    owner: root
    group: root
    mode: '0755'
- name: copy test file
  copy:
    src: "files/tests.py"
    dest: /root/tmp/tomcat-tests-files
    owner: root
    group: root
    mode: '0644'
