---
  - name: create build directory
    file:
      path: /root/tmp/tomcat-deploy-files
      state: directory
      owner: root
      group: root
      mode: '0755'
  - name: copy Dockerfile
    copy:
      src: "{{ project_path }}/files/Dockerfile"
      dest: /root/tmp/tomcat-deploy-files
      owner: root
      group: root
      mode: '0644'

  - name: build container image
    docker_image:
      name: "{{ image_name }}"
      tag: "{{ image_tag }}"
      build:
        path: /root/tmp/tomcat-deploy-files
        pull: no
        nocache: yes
      source: build

  - name: create build directory
    file:
      path: /root/tmp/tomcat-deploy-files
      state: absent
