---
- name: Create container
  docker_container:
    name: "{{ container_name }}"
    image: "{{ image_name }}:{{ image_tag }}"
    detach: yes
    cleanup: yes
    exposed_ports:
      - "{{ container_port }}"
    ports:
      - "{{ host_map_port }}:{{ container_port }}"

- name: Get container info
  docker_container_info:
    name: "{{ container_name }}"
  register: container_status

- name: Does container exist
  debug:
    msg: "The container testtomcat {{ 'is' if container_status.exists else 'is not' }} running"
