---
- name: create ansible user
  hosts: all
  vars_files:
    - "{{ project_path }}/vars/vars_ansible_user.yml"
  vars:
    ansible_user: root
  tasks:
  - name: "Create user"
    user:
      name: "{{ user_name }}"
      generate_ssh_key: "{{ user_generate_ssh_key }}"
      shell: "{{ user_shell }}"
  - name: "Enable including files from sudoers.d/"
    lineinfile:
      path: "/etc/sudoers"
      regexp: "^#includedir /etc/sudoers.d"
      line: "#includedir /etc/sudoers.d"
      state: "present"
      backup: True
    when: user_enable_passwordless_sudo
  - name: "Enable passwordless sudo"
    copy:
      content: "%{{ user_name }} ALL=(ALL) NOPASSWD:ALL"
      dest: "/etc/sudoers.d/{{ user_name }}"
      owner: "root"
      group: "root"
      mode: "0440"
    when: user_enable_passwordless_sudo

  - name: Set authorized key taken from file
    ansible.posix.authorized_key:
      user: ansible
      state: present
      key: "{{ lookup('file', path_to_public_key ) }}"

